apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonar-qube-web
  namespace: {{ .Values.namespace }}
  labels:
    name: sonar-qube-web
spec:
  rules:
  - host: {{ .Values.ingress.web }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: sonar-qube-web
            port: 
              number: 9000
