apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-qube-pvc
  namespace: {{.Values.namespace}}
  labels:
    app: sonar-qube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.storage.size}}