apiVersion: v1
kind: Service
metadata:
  name: sonar-qube
  namespace: {{.Values.namespace}}
  labels:
    app: sonar-qube
spec:
  selector:
    app: sonar-qube
  ports:
  - port: 9000
  type: NodePort