apiVersion: v1
kind: Service
metadata:
  name: postgres-api
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: postgresql
  ports:
  - name: postgres-api
    protocol: TCP
    port: 5432
type: NodePort